name: laravel

services:
    mysqldb:
        container_name: mysqldb
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql

    api:
        container_name: laravel-api
        image: laravel-api:007
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '80:8000'


volumes:
    mysql-data:
